# Taps

tap "buo/cask-upgrade"
tap "homebrew/bundle"
tap "homebrew/cask-drivers"
tap "homebrew/cask-fonts"

# Brews

brew "act"
brew "bash"
brew "bash-completion"
brew "bat"
brew "curl"
brew "exa"
brew "flac"
brew "lame"
brew "ffmpeg"
brew "git"
brew "gnupg"
brew "go"
brew "gradle"
brew "htop"
brew "nvm"
brew "pyenv"
brew "rsync"
brew "tree"
brew "websocat"
brew "wget"
brew "yarn"
brew "zsh"
brew "zsh-completions"

# Casks

cask "copyq"
cask "adobe-acrobat-reader"
cask "discord"
cask "docker"
cask "iterm2"
cask "rectangle"
cask "signal"
cask "fork"
cask "mullvadvpn"
cask "visual-studio-code"
cask "vlc"
casl "dotnet"
# cask "the-unarchiver"
# cask "disk-inventory-x"
# cask "mactex"

# Fonts

cask "font-caskaydia-cove-nerd-font"
cask "font-fira-code-nerd-font"
cask "font-handlee"
cask "font-hasklig"
cask "font-ibm-plex"
cask "font-inconsolata"
cask "font-jetbrains-mono"
cask "font-jetbrainsmono-nerd-font"
cask "font-jetbrainsmono-nerd-font-mono"
cask "font-linux-libertine"
cask "font-montserrat"
cask "font-noto-color-emoji"
cask "font-noto-emoji"
cask "font-noto-sans"
cask "font-noto-serif"
cask "font-open-sans"
cask "font-open-sans-condensed"
cask "font-pt-mono"
cask "font-pt-sans"
cask "font-pt-serif"
cask "font-redhat"
cask "font-roboto"
cask "font-roboto-condensed"
cask "font-roboto-mono"
cask "font-roboto-slab"
cask "font-signika-negative"
cask "font-source-code-pro"
cask "font-source-sans-pro"
cask "font-source-serif-pro"
cask "font-ubuntu"
cask "font-yanone-kaffeesatz"
